- name: configure backend server
  hosts: backend
  become: yes
  vars:
    login_host: backend.devopsme.online
  vars_prompt:
  - name: mysql_root_password
    prompt: please enter MySQL root password
    private: no
  tasks:
  - name: install nodejs Server
    ansible.builtin.dnf:
      name: nodejs
      state: latest
