- name: just practice
  hosts: localhost
  vars_prompt:
  - name: mysql_root_password
    prompt: please enter MySQL root password
    private: no
  tasks:
  - name: echo
    ansible.builtin.debug:
      msg : "{{mysql_root_password}}"