- name: configure db server
  hosts: db
  become: yes
  vars:
    login_host: db.devopsme.online
  vars_prompt:
  - name: mysql_root_password
    prompt: please enter MySQL root password
    private: no
  tasks:
  - name: install MySql Server
    ansible.builtin.debug:
      msg : "{{mysql_root_password}}""
      
